name: Build Electron app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./desktop

      - name: Build frontend
        run: |
          npm ci
          npm run build
        working-directory: ./frontend

      - name: Copy frontend build to desktop
        run: |
          rm -rf ./desktop/frontend
          cp -r ./frontend/build ./desktop/frontend

      - name: Build Electron app
        run: npm run dist
        working-directory: ./desktop

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: ./desktop/dist/
